admins:
  - email:    admin@barong.io
    password: changeme
    profile:
      first_name: Admin
      last_name: Admin
      city: Paris
      country: FR
      first_name: Admin
      last_name: Adminovich
      dob: 01/01/1970
      address: Kek st. 14
      postcode: 12345
      city: Paris
      country: FRA
      state: approved

applications:
  - name:         Peatio
    redirect_uri: http://peatio:8000/auth/barong/callback
    uid:          <%= SecureRandom.hex(32) %>
    secret:       <%= SecureRandom.hex(32) %>
    skipauth:     true
